[package]
name = "semver-4-winres"
version = "0.0.0"
description = "Parser of SemVer for use with winres."

license = "Apache-2.0"

readme = "README.md"
repository = "https://github.com/Chrimle/semver-4-winres"

authors = [
    "Christopher Molin <28791817+chrimle@users.noreply.github.com>"
]

keywords = [
    "semver",
    "winres"
]

edition = "2024"

[dependencies]
