[package]
name = "semver-4-winres"
version = "0.1.1"
description = "Parser of SemVer for use with winres."

license = "Apache-2.0"

readme = "docs/README.md"
repository = "https://github.com/Chrimle/semver-4-winres"
homepage = "https://chrimle.github.io/semver-4-winres/"

authors = [
    "Christopher Molin <28791817+chrimle@users.noreply.github.com>"
]

keywords = [
    "semver",
    "winres"
]

exclude = [
    ".github/",
    ".idea/",
    "docs/",
    ".gitattributes",
    ".gitignore"
]

edition = "2024"

[dependencies]
regex = "1.12.3"

[dev-dependencies]
test-case = "3.3.1"
